name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Vitest tests
        run: npm test

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Start server in background and wait for readiness
        run: |
          npm start &  # Start the server in the background
          # Wait for the server to be ready by checking http://localhost:3000
          npx wait-on http://localhost:3000
        env:
          PORT: 3000

      - name: Run Playwright tests
        run: npx playwright test e2e-tests
